version: '3.8'

services:
  web-server:
    image: yosdwi/digital-bast:latest
    container_name: digital-bast-web
    env_file: .env
    environment:
      - DB_URL=postgresql://celerates-admin:celerates911!!!@postgresql-local-postgre-1:5432/neondb
    command: ["python", "fastapi_server.py"]
    ports:
      - "127.0.0.1:8082:8000"
    networks:
      - digital-bast-network

  app:
    image: yosdwi/digital-bast:latest
    container_name: digital-bast-app
    env_file: .env
    environment:
      - HEALTHCHECK_URL=https://hc-ping.com/c67ead79-ffdd-4517-b360-fa03763a3df6
      - DB_URL=postgresql://celerates-admin:celerates911!!!@postgresql-local-postgre-1:5432/neondb
    command: ["python", "main.py", "--scheduler"]
    restart: unless-stopped
    networks:
      - digital-bast-network
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M

# volumes:
  # tinyauth_data:

networks:
  digital-bast-network:
    external: true

