from datetime import datetime, timedelta
from src import config
from src.classes.ClsNocoDBProcessor import ClsNocoDBProcessor
from src.classes.ClsIoTSheetProcessor import ClsIoTSheetProcessor
from src.utils.date_helper import get_configured_month_dates

def run():
    print("Executing Step 3 IoT: IoT Task Processing from Google Sheets")

    employee_table_id = config.NOCODB_TABLES.get("employee_data")
    tasklist_iot_table_id = config.NOCODB_TABLES.get("tasklist_iot")

    if not all([employee_table_id, tasklist_iot_table_id]):
        raise ValueError("Config for employee or tasklist_iot table ID is missing.")

    if not config.TASKLIST_IOT:
        raise ValueError("IoT tasklist configuration is missing.")

    nocodb_employee = ClsNocoDBProcessor(config.APP_BASE_ID, employee_table_id)
    nocodb_tasklist_iot = ClsNocoDBProcessor(config.APP_BASE_ID, tasklist_iot_table_id)
    iot_sheet_processor = ClsIoTSheetProcessor()

    try:
        # Get date range for processing
        start_date, end_date, _ = get_configured_month_dates()
        month_start_str = start_date.strftime('%Y-%m-%d')
        month_end_str = end_date.strftime('%Y-%m-%d')

        # --- Processing IoT Tasks from Google Sheets ---
        print("Processing IoT tasks from Google Sheets...")

        # Get IoT Operations employees
        iot_employees = nocodb_employee.get_all_employees(role_filter="IoT Operations")

        if not iot_employees:
            print("No IoT Operations employees found.")
            return

        # Read IoT tasks from Google Sheets
        iot_tasks_df = iot_sheet_processor.read_iot_tasks(month_start_str, month_end_str)

        if iot_tasks_df.empty:
            print("No IoT tasks found in the specified date range.")
            return

        # Process and upsert IoT tasks
        iot_records_to_create = []

        for _, row in iot_tasks_df.iterrows():
            # Map according to requirements:
            # Task List = Issue Description
            # Date = Date
            # Kategori = Issue Type
            # Requestor = "User"
            # Status = "Closed"
            # Unique Key = Date_Employee Id (generated by upsert method)
            # Start Time = Start Time
            # Response Time = Response Time
            # Close Time = Close Time
            # PIC Selection = First Responder

            record = {
                "Task List": row.get('Issue Description'),
                "Date": row.get('Date'),
                "Kategori": row.get('Issue Type'),
                "Requestor": "User",
                "Status": "Closed",
                "Start Date": row.get('Start Time'),  # Date + Start Time
                "End Date": row.get('Close Time'),    # Date + Close Time
                "Start Time": row.get('Start Time'),
                "Response Time": row.get('Response Time'),
                "Close Time": row.get('Close Time'),
                "PIC Selection": row.get('First Responder'),
            }
            iot_records_to_create.append(record)

        success_count = 0
        failed_count = 0

        for i, record in enumerate(iot_records_to_create):
            result = nocodb_tasklist_iot.upsert_iot_task(record, iot_employees)
            if result:
                success_count += 1
            else:
                failed_count += 1
                if failed_count <= 3:  # Show first 3 failures for debugging
                    print(f"Failed record {i+1}: Date: {record.get('Date')}, Task: {record.get('Task List', '')[:50]}")

        print(f"Successfully upserted {success_count}/{len(iot_records_to_create)} IoT task records.")
        if failed_count > 0:
            print(f"Failed: {failed_count} records (check logs above for details)")

        print("Step 3 IoT: Completed.")

    except Exception as e:
        print(f"Step 3 IoT: Failed with error: {e}")
        raise