SELECT
    login,
    nrp,
    nama,
    project_id,
    project_name,
    tracker_id,
    tracker_name,
    isu_id,
    isu_subject,
    description,
    start_date,
    due_date,
    plan_date,
    created_on,
    closed_on,
    actual_date,
    category_id,
    category_name,
    status_id,
    status_desc,
    assigned_to_id,
    priority_id,
    priority_name,
    author_id,
    author_login,
    author_name,
    updated_on,
    done_ratio,
    estimated_hours,
    parent_id,
    date_inserted,
    date_updated,
    digi_id,
    digi_desc,
    digi_value
FROM DB_SATUPAMA_CIS.dbo.cis_jiep_tbl_redmine_bigdata_all_wi_digi
WHERE start_date >= ? AND start_date <= ?
   OR created_on >= ? AND created_on <= ?
ORDER BY start_date DESC, created_on DESC;
